<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="TeamAndSpite.fs" />
    <Compile Include="Coordinates.fs"  />
    <Compile Include="Locating.fs"     />
    <Compile Include="Helpers.fs"      />
    <Compile Include="Development.fs"  />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Chess.Domain.C" />
  </ItemGroup>

</Project>
